### ISSUE TITLE
How can I close the Chat on the Customer page and came back to the Chat?

### ISSUE THREAD

**Issue by WintecRemoteDiagnostic** [jifeline-networks/openOBD#5]
Hey,
how can I close the Chat on the Customer page and came back to the Chat? Over the Session handler? I found not the way

**Comment by Frank-openOBD** [comment]
We have a command to close the User Interaction: `ui_handler.stop_stream()`.
An example piece of code can be found here: https://docs.openobd.com/latest/examples/ui/

**Comment by martinw2024** [comment]
Hi Frank, Ive send you an email with the same question. Demo.py doesnt bring the customer back to the main chat. I can confirm that. Could you take a look into it?

**Comment by Frank-openOBD** [comment]
Thanks for reaching out. We have identified a minor bug. The UI does not close if an ‘error’ occurs, e.g. the client cancelling the stream, although this is the only way to close the stream. The CAN service does implement this properly, so we don't know exactly why this was not done with the UI. We will add this and release a new version tonight.

**Comment by martinw2024** [comment]
ok, but the code runs through normally without creating any error, but UI is not closing either. Console states "stream closed" too. FYI

**Comment by Frank-openOBD** [comment]
Please make sure you download our latest openOBD Python package v1.15.2.
