### ISSUE TITLE
Operator UI not working

### ISSUE THREAD

**Issue by martinw2024** [jifeline-networks/openOBD#7]
Hello Frank,

today I tried your Operator UI example.

When starting script, the session doesnt open.

It just goes up to "refreshing auth. token" state.

When I take out the Operator UI elements out of the code, then its working fine.

any idea?

thats my lib. versions:

certifi            2024.8.30   
chardet            5.2.0       
charset-normalizer 3.3.2       
et-xmlfile         1.1.0       
grpcio             1.60.1
grpcio-tools       1.60.1
idna               3.10
numpy              1.26.2
openobd            1.15.2
openobd-protocol   1.16.0
openobd-utils      1.15.2
openpyxl           3.1.2
pandas             2.1.4
Pillow             10.1.0
pip                23.2.1
protobuf           4.25.5
python-dateutil    2.8.2
python-dotenv      1.0.1
pytz               2023.3.post1
reportlab          4.2.2
requests           2.32.3
setuptools         75.1.0
six                1.16.0
tzdata             2023.3
urllib3            2.2.3

**Comment by Frank-openOBD** [comment]
Please provide us with a bit more context (some lines of your code) and a screenshot of the error you receive.

**Comment by martinw2024** [comment]
its your example code:

```
from openobd import *


# Start an openOBD session on a ticket
openobd = OpenOBD()
openobd_session = openobd.start_session_on_ticket(TICKET_ID)    # The ticket ID needs to be filled in (as a string)

# Start the SessionTokenHandler to ensure the openOBD session remains authenticated
SessionTokenHandler(openobd_session)

# Create a UiHandler object for the customer/user (which is the default)
customer_ui = UiHandler(openobd_session)
# Create a second UiHandler object, explicitly stating that it should be shown to the operator
operator_ui = UiHandler(openobd_session, target=InterfaceType.INTERFACE_OPERATOR)

# Inform the operator that the customer is entering a PIN
operator_ui.show_ui(Label(label="The customer is currently entering a PIN."))
while True:
    # Wait for the customer to enter a PIN
    pin = customer_ui.show_ui(FreeText(label="Please enter the PIN of the vehicle."))

    # Tell the customer to wait while asking the operator to check the PIN
    customer_ui.show_ui(Label(label="Please wait while the operator checks if the PIN is correct."))
    if operator_ui.show_ui(YesNo(label=f"The customer entered the PIN 'f{pin}'. Is this correct?")):
        # Inform both the customer and operator that the procedure is finished
        operator_ui.show_ui(Label(label="The procedure is finished."))
        customer_ui.show_ui(Label(label="Your PIN is correct. The procedure is finished.", minimal_display_time=3))
        break
    else:
        # Inform both the operator and customer that the customer needs to enter a PIN again
        operator_ui.show_ui(Label(label="The customer is entering a PIN again."))
        customer_ui.show_ui(Label(label="The operator has indicated that the entered PIN is incorrect. Please try again.", minimal_display_time=5))

# Close both UIs
customer_ui.stop_stream()
operator_ui.stop_stream()

# Close the session with a successful result
result = ServiceResult(result=[Result.RESULT_SUCCESS])
openobd_session.finish(result)
```

after starting it doesnt create and error, but it doesnt get any further than

[+] refreshing token.....

When commenting out all operator UI codelines its runs as normal. Of course I added a running ticket ID as string

**Comment by Frank-openOBD** [comment]
Did you open the operator UI via the Partner Portal/Ticket Workspace?

**Comment by martinw2024** [comment]
no, i just ran the code and expected that the UI inside the ticket portal changes automatically like with the customer UI. What do I need to do? Its not mentioned on GRPC ressources.

BR

Martin

**Comment by Frank-openOBD** [comment]
There a re two types of User Interface:

- Customer UI, runs in the Customer Portal
- Operator UI, runs in the Ticket Workspace

I will make sure we improve our documentation around this theme.

**Comment by martinw2024** [comment]
ok, but am I right when I say "while im inside the ticket workspace, the script should trigger something"?
I expect something similiar like when im outsourcing something to the robot. Or what do you mean exactly with :

" Did you open the operator UI via the Partner Portal/Ticket Workspace?

BR

Martin

**Comment by Frank-openOBD** [comment]
We concluded that we need to make some changes to the Ticket Workspace to be sure that the Operator UI is shown correctly. We have added a user story to our backlog for this issue. Thanks for catching this one.
